thucnh071203/FamilyFarm

FamilyFarm.API/Controllers/AuthenticationController.cs, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Interfaces/IAccountService.cs, FamilyFarm.BusinessLogic/Interfaces/IAuthenticationService.cs, FamilyFarm.BusinessLogic/Services/AccountService.cs, FamilyFarm.BusinessLogic/Services/AuthenticationService.cs, FamilyFarm.DataAccess/DAOs/AccountDAO.cs, FamilyFarm.Models/DTOs/Request/ChangePasswordDTO.cs, FamilyFarm.Models/DTOs/Request/LoginGoogleRequestDTO.cs, FamilyFarm.Models/DTOs/Request/SetPasswordDTO.cs, FamilyFarm.Repositories/Implementations/AccountRepository.cs, FamilyFarm.Repositories/Interfaces/IAccountRepository.cs
add login with google, set password, change password
=> add login with google, set password, change password

FamilyFarm.DataAccess/DAOs/AccountDAO.cs, FamilyFarm.DataAccess/DAOs/ServiceDAO.cs, FamilyFarm.Models/Models/BookingService.cs, FamilyFarm.Models/Models/Category.cs, FamilyFarm.Models/Models/CategoryReaction.cs, FamilyFarm.Models/Models/CategoryService.cs, FamilyFarm.Models/Models/Chat.cs, FamilyFarm.Models/Models/Comment.cs, FamilyFarm.Models/Models/Friend.cs, FamilyFarm.Models/Models/Group.cs, FamilyFarm.Models/Models/GroupMember.cs, FamilyFarm.Models/Models/GroupRole.cs, FamilyFarm.Models/Models/HashTag.cs, FamilyFarm.Models/Models/Notification.cs, FamilyFarm.Models/Models/NotificationStatus.cs, FamilyFarm.Models/Models/PostCategory.cs, FamilyFarm.Models/Models/PostImage.cs, FamilyFarm.Models/Models/Process.cs, FamilyFarm.Models/Models/ProcessStep.cs, FamilyFarm.Models/Models/ProcessStepResults.cs, FamilyFarm.Models/Models/ReactionComment.cs, FamilyFarm.Models/Models/ReactionPost.cs, FamilyFarm.Models/Models/SavedPost.cs, FamilyFarm.Models/Models/Service.cs, FamilyFarm.Models/Models/SharePostTag.cs
=> update string Id in Models

FamilyFarm.API/Controllers/CommentController.cs, FamilyFarm.API/Controllers/ReactionController.cs, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Interfaces/IReactionPostService.cs, FamilyFarm.BusinessLogic/Services/ReactionPostService.cs, FamilyFarm.DataAccess/DAOs/CategoryReactionDAO.cs, FamilyFarm.DataAccess/DAOs/CommentDAO.cs, FamilyFarm.DataAccess/DAOs/ReactionPostDAO.cs, FamilyFarm.Models/DTOs/Request/ReactionRequestDTO.cs, FamilyFarm.Models/Models/ReactionPost.cs, FamilyFarm.Repositories/Implementations/CategoryReactionRepository.cs, FamilyFarm.Repositories/Implementations/ReactionPostRepository.cs, FamilyFarm.Repositories/Interfaces/ICategoryReactionRepository.cs, FamilyFarm.Repositories/Interfaces/IReactionPostRepository.cs
modified create comment, add reaction-post
=> modified create comment, add reaction-post

FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.API/Controllers/ReportController.cs, FamilyFarm.API/Program.cs, FamilyFarm.API/appsettings.json, FamilyFarm.BusinessLogic/Interfaces/IPostService.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.DataAccess/DAOs/PostDAO.cs, FamilyFarm.Models/Models/Post.cs, FamilyFarm.Repositories/Implementations/PostRepository.cs, FamilyFarm.Repositories/Interfaces/IPostRepository.cs
Search post by keyword or category
=> Search post by keyword or category

FamilyFarm.API/Controllers/AuthenticationController.cs, FamilyFarm.API/Controllers/FriendController.cs, FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Interfaces/IAuthenticationService.cs, FamilyFarm.BusinessLogic/Services/AuthenticationService.cs, FamilyFarm.DataAccess/DAOs/RoleDAO.cs, FamilyFarm.Models/DTOs/Request/EmailRequestDTO.cs, FamilyFarm.Models/DTOs/Response/UserClaimsReponseDTO.cs, FamilyFarm.Repositories/Implementations/RoleRepository.cs, FamilyFarm.Repositories/Interfaces/IRoleRepository.cs
update GetDataFromToken. Get Username, Email, AccId, RoleId, RoleName
=> update GetDataFromToken. Get Username, Email, AccId, RoleId, RoleName

FamilyFarm.API/Controllers/AuthenticationController.cs, FamilyFarm.API/Controllers/ChatController.cs, FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.API/Controllers/ReactionController.cs, FamilyFarm.API/FamilyFarm.API.csproj, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/FamilyFarm.BusinessLogic.csproj, FamilyFarm.BusinessLogic/Hubs/ChatHub.cs, FamilyFarm.BusinessLogic/Interfaces/IChatService.cs, FamilyFarm.BusinessLogic/Services/ChatService.cs, FamilyFarm.BusinessLogic/Services/CustomUserIdProvider.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.DataAccess/DAOs/ChatDAO.cs, FamilyFarm.DataAccess/DAOs/ChatDetailDAO.cs, FamilyFarm.DataAccess/DAOs/PostDAO.cs, FamilyFarm.Models/DTOs/Request/StartChatRequestDTO.cs, FamilyFarm.Models/Models/ChatDetail.cs, FamilyFarm.Repositories/Implementations/ChatDetailRepository.cs, FamilyFarm.Repositories/Implementations/ChatRepository.cs, FamilyFarm.Repositories/Interfaces/IChatDetailRepository.cs, FamilyFarm.Repositories/Interfaces/IChatRepository.cs
add crud realtime chat, have not authorize yet
=> add crud realtime chat, have not authorize yet

FamilyFarm.API/Controllers/ChatController.cs, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Interfaces/IChatService.cs, FamilyFarm.BusinessLogic/Services/ChatService.cs, FamilyFarm.DataAccess/DAOs/ChatDAO.cs, FamilyFarm.DataAccess/DAOs/ChatDetailDAO.cs, FamilyFarm.Models/DTOs/Request/SendMessageRequestDTO.cs, FamilyFarm.Models/DTOs/Request/StartChatRequestDTO.cs, FamilyFarm.Models/DTOs/Response/SendMessageResponseDTO.cs, FamilyFarm.Models/FamilyFarm.Models.csproj, FamilyFarm.Models/Mapper/MappingProfile.cs, FamilyFarm.Models/Models/Chat.cs, FamilyFarm.Models/Models/ChatDetail.cs
add auto mapper, Authorize for chat
=> add auto mapper, Authorize for chat

FamilyFarm.API/Controllers/ChatController.cs, FamilyFarm.BusinessLogic/Hubs/ChatHub.cs, FamilyFarm.BusinessLogic/Interfaces/IChatService.cs, FamilyFarm.BusinessLogic/Services/AuthenticationService.cs, FamilyFarm.BusinessLogic/Services/ChatService.cs, FamilyFarm.DataAccess/DAOs/ChatDetailDAO.cs, FamilyFarm.Models/DTOs/Request/SendMessageRequestDTO.cs, FamilyFarm.Models/Mapper/MappingProfile.cs, FamilyFarm.Models/Models/ChatDetail.cs, FamilyFarm.Repositories/Implementations/ChatDetailRepository.cs, FamilyFarm.Repositories/Interfaces/IChatDetailRepository.cs
=> add send message with file

FamilyFarm.API/Controllers/GroupMemberController.cs, FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.BusinessLogic/Interfaces/IGroupMemberService.cs, FamilyFarm.BusinessLogic/Interfaces/IPostService.cs, FamilyFarm.BusinessLogic/Services/GroupMemberService.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.DataAccess/DAOs/GroupMemberDAO.cs, FamilyFarm.DataAccess/DAOs/PostDAO.cs, FamilyFarm.Models/DTOs/Request/RequestToJoinGroupRequestDTO.cs, FamilyFarm.Models/DTOs/Response/GroupMemberResponse.cs, FamilyFarm.Models/Mapper/GroupMemberRequest.cs, FamilyFarm.Repositories/Implementations/GroupMemberRepository.cs, FamilyFarm.Repositories/Implementations/PostRepository.cs, FamilyFarm.Repositories/Interfaces/IGroupMemberRepository.cs, FamilyFarm.Repositories/Interfaces/IPostRepository.cs
Search user in group (fullName)
=> View list user in group

FamilyFarm.API/Controllers/NotificationController.cs, FamilyFarm.API/Controllers/ReactionController.cs, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Hubs/ChatHub.cs, FamilyFarm.BusinessLogic/Hubs/NotificationHub.cs, FamilyFarm.BusinessLogic/Interfaces/INotificationService.cs, FamilyFarm.BusinessLogic/Interfaces/IReactionService.cs, FamilyFarm.BusinessLogic/Services/ChatService.cs, FamilyFarm.BusinessLogic/Services/NotificationService.cs, FamilyFarm.BusinessLogic/Services/ReactionService.cs, FamilyFarm.DataAccess/DAOs/NotificationDAO.cs, FamilyFarm.DataAccess/DAOs/NotificationStatusDAO.cs, FamilyFarm.DataAccess/DAOs/ReactionDAO.cs, FamilyFarm.Models/DTOs/Request/SendNotificationRequestDTO.cs, FamilyFarm.Models/DTOs/Response/ListNotifiResponseDTO.cs, FamilyFarm.Models/DTOs/Response/ListReactionResponseDTO.cs, FamilyFarm.Models/DTOs/Response/SendNotificationResponseDTO.cs, FamilyFarm.Models/Mapper/MappingProfile.cs, FamilyFarm.Models/Models/Notification.cs, FamilyFarm.Models/Models/NotificationStatus.cs, FamilyFarm.Models/Models/Reaction.cs, FamilyFarm.Repositories/Implementations/NotificationRepository.cs, FamilyFarm.Repositories/Implementations/NotificationStatusRepository.cs, FamilyFarm.Repositories/Interfaces/INotificationRepository.cs, FamilyFarm.Repositories/Interfaces/INotificationStatusRepository.cs
Add realtime Notification and modified reaction, chat
=> Add realtime Notification and modified reaction, chat

FamilyFarm.API/Controllers/ReactionController.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.Models/DTOs/Request/SendNotificationRequestDTO.cs
=> modified reaction

FamilyFarm.API/Controllers/CommentController.cs, FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.API/Controllers/SharePostController.cs, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Interfaces/ICommentService.cs, FamilyFarm.BusinessLogic/Interfaces/IPostService.cs, FamilyFarm.BusinessLogic/Interfaces/ISharePostService.cs, FamilyFarm.BusinessLogic/Services/CommentService.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.BusinessLogic/Services/SharePostService.cs, FamilyFarm.DataAccess/DAOs/PostDAO.cs, FamilyFarm.DataAccess/DAOs/SharePostDAO.cs, FamilyFarm.DataAccess/DAOs/SharePostTagDAO.cs, FamilyFarm.Models/DTOs/EntityDTO/SharePostDTO.cs, FamilyFarm.Models/DTOs/Request/SharePostRequestDTO.cs, FamilyFarm.Models/DTOs/Response/ListPostResponseDTO.cs, FamilyFarm.Models/DTOs/Response/PostResponseDTO.cs, FamilyFarm.Models/DTOs/Response/SharePostResponseDTO.cs, FamilyFarm.Models/Models/SharePost.cs, FamilyFarm.Models/Models/SharePostTag.cs, FamilyFarm.Repositories/Implementations/PostRepository.cs, FamilyFarm.Repositories/Implementations/SharePostRepository.cs, FamilyFarm.Repositories/Implementations/SharePostTagRepository.cs, FamilyFarm.Repositories/Interfaces/IPostRepository.cs, FamilyFarm.Repositories/Interfaces/ISharePostRepository.cs, FamilyFarm.Repositories/Interfaces/ISharePostTagRepository.cs
add share post, modified post service
=> add share post, modified post service

FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.API/Controllers/SharePostController.cs, FamilyFarm.BusinessLogic/Interfaces/ISharePostService.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.BusinessLogic/Services/SharePostService.cs, FamilyFarm.DataAccess/DAOs/SharePostDAO.cs, FamilyFarm.Models/DTOs/Request/SharePostRequestDTO.cs, FamilyFarm.Models/DTOs/Request/UpdateSharePostRequestDTO.cs, FamilyFarm.Models/Models/SharePost.cs, FamilyFarm.Repositories/Implementations/SharePostRepository.cs, FamilyFarm.Repositories/Interfaces/ISharePostRepository.cs
=> update, delete share post

FamilyFarm.API/Controllers/AuthenticationController.cs, FamilyFarm.API/Controllers/BookingServiceController.cs, FamilyFarm.API/Controllers/CategoryPostController.cs, FamilyFarm.API/Controllers/CategoryReactionController.cs, FamilyFarm.API/Controllers/SearchHistoryController.cs
=> modified api endpoint

FamilyFarm.BusinessLogic/Services/ChatService.cs, FamilyFarm.BusinessLogic/Services/NotificationTemplateService.cs, FamilyFarm.Models/DTOs/EntityDTO/ChatDTO.cs, FamilyFarm.Models/DTOs/Response/ListChatResponseDTO.cs, FamilyFarm.Models/Mapper/MappingProfile.cs
=> modified list chat

FamilyFarm.API/Controllers/ChatController.cs, FamilyFarm.BusinessLogic/Hubs/ChatHub.cs, FamilyFarm.BusinessLogic/Interfaces/IChatService.cs, FamilyFarm.BusinessLogic/Services/AuthenticationService.cs, FamilyFarm.BusinessLogic/Services/ChatService.cs, FamilyFarm.DataAccess/DAOs/ChatDetailDAO.cs, FamilyFarm.Models/DTOs/EntityDTO/ChatDTO.cs, FamilyFarm.Models/DTOs/Response/ListChatDetailsResponseDTO.cs, FamilyFarm.Models/DTOs/Response/LoginResponseDTO.cs, FamilyFarm.Models/Mapper/MappingProfile.cs, FamilyFarm.Repositories/Implementations/ChatDetailRepository.cs, FamilyFarm.Repositories/Interfaces/IChatDetailRepository.cs
modified chat service, chat hub
=> modified chat service, chat hub

FamilyFarm.API/appsettings.json
=> update jwt token

FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.BusinessLogic/Services/SavedPostService.cs, FamilyFarm.Models/Mapper/PostMapper.cs, FamilyFarm.Models/Models/PostTag.cs
Fix 2: add OwnerPost into MyProfileDTO for get list post and saved post.
=> Fix 1: add attribute fullname, avatar into PostTag.

FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.DataAccess/DAOs/SharePostDAO.cs, FamilyFarm.Models/Mapper/PostMapper.cs, FamilyFarm.Repositories/Implementations/SharePostRepository.cs, FamilyFarm.Repositories/Interfaces/ISharePostRepository.cs
modified post mapper to response commentCount, reactionCount, ShareCount
=> modified post mapper to response commentCount, reactionCount, ShareCount

FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Hubs/NotificationHub.cs, FamilyFarm.BusinessLogic/Services/ChatService.cs, FamilyFarm.BusinessLogic/Services/NotificationService.cs, FamilyFarm.Models/DTOs/EntityDTO/NotificationDTO.cs, FamilyFarm.Models/Mapper/MappingProfile.cs
modified notification with signalR
=> modified notification with signalR

FamilyFarm.API/Controllers/AuthenticationController.cs, FamilyFarm.Models/DTOs/EntityDTO/MyProfileDTO.cs
=> add otp to MyProfileDTO

FamilyFarm.API/Controllers/AccountController.cs, FamilyFarm.BusinessLogic/Interfaces/IAccountService.cs, FamilyFarm.BusinessLogic/Services/AccountService.cs, FamilyFarm.BusinessLogic/Services/AuthenticationService.cs, FamilyFarm.DataAccess/DAOs/AccountDAO.cs, FamilyFarm.Models/DTOs/Request/UpdateBackgroundRequestDTO.cs, FamilyFarm.Models/DTOs/Response/UpdateBackgroundResponseDTO.cs, FamilyFarm.Repositories/Implementations/AccountRepository.cs, FamilyFarm.Repositories/Interfaces/IAccountRepository.cs
=> add change background api

FamilyFarm.BusinessLogic/Services/SharePostService.cs, FamilyFarm.DataAccess/DAOs/SharePostDAO.cs, FamilyFarm.Models/DTOs/Request/SharePostRequestDTO.cs
=> modified create share post

FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.BusinessLogic/Services/SharePostService.cs, FamilyFarm.Models/Mapper/SharePostMapper.cs, FamilyFarm.Models/Models/SharePostTag.cs
=> modified share post mapper

FamilyFarm.API/Controllers/FriendController.cs, FamilyFarm.BusinessLogic/Interfaces/IFriendService.cs, FamilyFarm.BusinessLogic/Services/FriendService.cs, FamilyFarm.DataAccess/DAOs/FriendDAO.cs, FamilyFarm.Repositories/Implementations/FriendRepository.cs, FamilyFarm.Repositories/Interfaces/IFriendRepository.cs
=> add check is friend endpoint

FamilyFarm.API/Controllers/ProcessController.cs, FamilyFarm.API/Controllers/ProcessStepController.cs, FamilyFarm.BusinessLogic/Interfaces/IProcessService.cs, FamilyFarm.BusinessLogic/Services/ProcessService.cs, FamilyFarm.DataAccess/DAOs/ProcessStepDAO.cs, FamilyFarm.Models/DTOs/Request/ProcessStepResultRequestDTO.cs, FamilyFarm.Models/DTOs/Response/ProcessStepResultResponseDTO.cs, FamilyFarm.Models/Mapper/ProcessOriginMapper.cs, FamilyFarm.Models/Mapper/ProcessStepResultMapper.cs, FamilyFarm.Repositories/Implementations/ProcessStepRepository.cs, FamilyFarm.Repositories/Interfaces/IProcessStepRepository.cs
add api create process step result, get result
=> add api create process step result, get result

FamilyFarm.API/Controllers/ReviewController.cs, FamilyFarm.API/Program.cs, FamilyFarm.BusinessLogic/Interfaces/IReviewService.cs, FamilyFarm.BusinessLogic/Services/ReviewService.cs, FamilyFarm.BusinessLogic/Services/ServicingService.cs, FamilyFarm.DataAccess/DAOs/ReviewDAO.cs, FamilyFarm.Models/DTOs/EntityDTO/ReviewDTO.cs, FamilyFarm.Models/DTOs/EntityDTO/ReviewSummaryDTO.cs, FamilyFarm.Models/DTOs/Request/ReviewRequestDTO.cs, FamilyFarm.Models/DTOs/Response/ListReviewResponseDTO.cs, FamilyFarm.Models/DTOs/Response/ReviewResponseDTO.cs, FamilyFarm.Models/Mapper/MappingProfile.cs, FamilyFarm.Models/Mapper/ServiceMapper.cs, FamilyFarm.Models/Models/Review.cs, FamilyFarm.Repositories/Implementations/ReviewRepository.cs, FamilyFarm.Repositories/Interfaces/IReviewRepository.cs
=> add review service

FamilyFarm.API/Controllers/AuthenticationController.cs, FamilyFarm.Tests/AuthenticationControllerTests.cs, FamilyFarm.Tests/FamilyFarm.Tests.csproj, FamilyFarm.sln
=> add test class lib

FamilyFarm.Tests/AuthenticationTest/LoginTests.cs
=> modified test login

FamilyFarm.API/Controllers/ChatController.cs, FamilyFarm.API/Controllers/CommentController.cs, FamilyFarm.API/Controllers/ReportController.cs, FamilyFarm.Models/DTOs/Response/MiniAccountDTO.cs, FamilyFarm.Models/Models/CategoryReaction.cs, FamilyFarm.Tests/AccountTest/ChangeAvatarTest.cs, FamilyFarm.Tests/AuthenticationTest/LoginTests.cs, FamilyFarm.Tests/ChatTest/DeleteChatHistoryTests.cs, FamilyFarm.Tests/ChatTest/RecallMessageTests.cs, FamilyFarm.Tests/ChatTest/SearchChatTests.cs, FamilyFarm.Tests/ChatTest/SeenMessageTests.cs, FamilyFarm.Tests/ChatTest/SendMessageTests.cs, FamilyFarm.Tests/ChatTest/ViewChatDetailTests.cs, FamilyFarm.Tests/ChatTest/ViewListChatTests.cs, FamilyFarm.Tests/CommentTest/CreateCommentTest.cs, FamilyFarm.Tests/CommentTest/DeleteCommentTest.cs, FamilyFarm.Tests/CommentTest/EditCommentTest.cs, FamilyFarm.Tests/CommentTest/ListCommentTest.cs, FamilyFarm.Tests/NotificationTest/MarkAllAsReadTests.cs, FamilyFarm.Tests/NotificationTest/MarkAsReadTests.cs, FamilyFarm.Tests/NotificationTest/ViewListNotificationsTests.cs, FamilyFarm.Tests/PostTest/ReportPostTest.cs, FamilyFarm.Tests/PostTest/SearchPostTest.cs, FamilyFarm.Tests/ReactionTest/ListReactionTests.cs, FamilyFarm.Tests/ReactionTest/ReactToCommentTests.cs, FamilyFarm.Tests/ReactionTest/ReactToPostTests.cs, FamilyFarm.Tests/ReportTest/AcceptPostReportTests.cs, FamilyFarm.Tests/ReportTest/RejectReportRequestTests.cs, FamilyFarm.Tests/ReportTest/ViewListReportPostTests.cs
=> add unit test cua thuc

FamilyFarm.API/Controllers/PaymentController.cs, FamilyFarm.Tests/PaymentTest/PayToExpertTests.cs, FamilyFarm.Tests/PaymentTest/ViewListPaymentTests.cs, FamilyFarm.Tests/ReviewTest/AddReviewOfServiceTests.cs, FamilyFarm.Tests/ReviewTest/ViewListReviewTests.cs
=> add payment test

FamilyFarm.API/Controllers/ReportController.cs
=> modified report controller

FamilyFarm.sln
=> add package AI chatbot

FamilyFarm.Models/Models/CategoryReaction.cs
=> modified category reaction

FamilyFarm.API/Controllers/PostController.cs, FamilyFarm.API/Controllers/SharePostController.cs, FamilyFarm.BusinessLogic/Interfaces/IPostService.cs, FamilyFarm.BusinessLogic/Interfaces/ISharePostService.cs, FamilyFarm.BusinessLogic/Services/PostService.cs, FamilyFarm.BusinessLogic/Services/SharePostService.cs, FamilyFarm.DataAccess/DAOs/SharePostDAO.cs, FamilyFarm.Repositories/Implementations/SharePostRepository.cs, FamilyFarm.Repositories/Interfaces/ISharePostRepository.cs
modified get list post with share in personal page
=> modified get list post with share in personal page

FamilyFarm.API/Controllers/FriendController.cs, FamilyFarm.BusinessLogic/Interfaces/IFriendService.cs, FamilyFarm.BusinessLogic/Services/FriendService.cs, FamilyFarm.DataAccess/DAOs/FriendDAO.cs, FamilyFarm.Repositories/Implementations/FriendRepository.cs, FamilyFarm.Repositories/Interfaces/IFriendRepository.cs
=> add search user

FamilyFarm.API/Controllers/AccountController.cs, FamilyFarm.API/Controllers/AuthenticationController.cs, FamilyFarm.BusinessLogic/Services/EmailTemplateHelper.cs
=> add send email account censor
